@baseURL = http://localhost:3002
@testTOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Listar todos os pontos persistidos
GET {{baseURL}}/api/geo
Authorization: {{testTOKEN}}
### return
# [
#   {
#     "lat": "40.748817",
#     "lon": "-73.985428",
#     "info": { ... }
#   }
# ]

### Consulta de reverse geocoding para um ponto específico
GET {{baseURL}}/api/geo/reverse?lat=40.748817&lon=-73.985428
Authorization: {{testTOKEN}}
### return
# {
#   "lat": "40.7489855",
#   "lon": "-73.9853975",
#   "info": { ... }
# }

### Criar um novo ponto geográfico
POST {{baseURL}}/api/geo
Authorization: {{testTOKEN}}
Content-Type: application/json

{
  "lat": 40.7128,
  "lon": -74.0060
}

### Buscar ponto geográfico por ID
GET {{baseURL}}/api/geo/468
Authorization: {{testTOKEN}}

### Atualizar ponto geográfico por ID
PUT {{baseURL}}/api/geo/467
Authorization: {{testTOKEN}}
Content-Type: application/json

{
  "lat": 40.73061,
  "lon": -73.935242
}

### Deletar ponto geográfico por ID
DELETE {{baseURL}}/api/geo/467
Authorization: {{testTOKEN}}
