@baseURL = http://localhost:3002

### Health
GET {{baseURL}}

### Polygons - List all
GET {{baseURL}}/api/polygons
### Return 
# [
#   {
#     "id": 1,
#     "name": "Meu Polígono",
#     "coordinates": "[[-46.63331,-23.55052],[-46.634,-23.5505],[-46.6335,-23.551]]",
#     "properties": {
#       "totalPoints": 3,
#       "sum": 30,
#       "average": 10,
#       "median": 10
#     }
#   },
#   {
#     "id": 2,


### Polygons - Get by ID
GET {{baseURL}}/api/polygons/1

### Return

# {
#   "id": 1,
#   "name": "Meu Polígono",
#   "coordinates": "[[-46.63331,-23.55052],[-46.634,-23.5505],[-46.6335,-23.551]]",
#   "properties": {
#     "totalPoints": 3,
#     "sum": 30,
#     "average": 10,
#     "median": 10
#   }
# }

### Polygons - Create
POST {{baseURL}}/api/polygons
Content-Type: application/json

{
  "name": "Meu Polígono",
  "coordinates": [
    [ -46.63331, -23.55052 ],
    [ -46.63400, -23.55050 ],
    [ -46.63350, -23.55100 ]
  ],
  "pointsInside": [5, 10, 15] 
}

### Return 
# {
#   "id": 8,
#   "name": "Meu Polígono",
#   "coordinates": "[[-46.63331,-23.55052],[-46.634,-23.5505],[-46.6335,-23.551]]",
#   "properties": {
#     "totalPoints": 3,
#     "sum": 30,
#     "average": 10,
#     "median": 10
#   }
# }

### Polygons - Update
PUT {{baseURL}}/api/polygons/1
Content-Type: application/json

{
  "name": "Polígono Atualizado",
  "coordinates": [
    [ -46.63331, -23.55052 ],
    [ -46.63450, -23.55000 ],
    [ -46.63370, -23.55120 ]
  ],
  "pointsInside": [7, 8, 12]
}

### Return 


# {
#   "id": 1,
#   "name": "Polígono Atualizado",
#   "coordinates": "[[-46.63331,-23.55052],[-46.6345,-23.55],[-46.6337,-23.5512]]",
#   "properties": {
#     "totalPoints": 3,
#     "sum": 27,
#     "average": 9,
#     "median": 8
#   }
# }

### Polygons - Delete
DELETE {{baseURL}}/api/polygons/1
